### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by 14150808ul** [14150808ul/SystemsAnalysis#4]
Map Package

**Comment by BruceConstantine** [comment]
[tsf.zip](https://github.com/14150808ul/SystemsAnalysis/files/841769/tsf.zip)

**Comment by BruceConstantine** [comment]
This is the version can speed up

**Comment by ghost** [comment]
Hey dude this is cool but the implementation is a bit all over the place and somethings should be in different packages and some packages itself shouldn't exist
